/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Usuarios;
import Classes.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author terra
 */
public class InsUser extends javax.swing.JDialog {

    /**
     * Creates new form ins_user
     */
    int continuar = 0;

    public InsUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nueva Cuenta");
        txt_username.requestFocus();
        setIconImage(new ConfigDat().getImageIcon().getImage());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public int getContinuar() {
        return continuar;
    }

    public void asign_datos() {
        txt_id.setText(new Usuarios().genID());
    }

    public void setDatFirstUse() {
        jLabel1.setText("CREAR CUENTA ADMIN");
        asign_datos();
        combo_accslvl.setSelectedIndex(1);
        combo_accslvl.enable(false);
        this.setDefaultCloseOperation(0);
        txt_username.setText("admin");
        txt_pass.requestFocus();

    }

    boolean ok = false;

    public boolean isOk() {
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        combo_accslvl = new javax.swing.JComboBox<>();
        txt_pass = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txt_rep_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nueva cuenta");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Datos de cuenta: ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setText("Puesto");

        combo_accslvl.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        combo_accslvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Administrador" }));
        combo_accslvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_accslvlActionPerformed(evt);
            }
        });

        txt_pass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setText("Rep. Cont");

        txt_rep_pass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_rep_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rep_passActionPerformed(evt);
            }
        });
        txt_rep_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rep_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rep_passKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Identificador");

        txt_username.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("CONTINUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR CUENTA NUEVA");

        txt_id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_id.setText("000000000000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_username))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pass)
                                    .addComponent(txt_rep_pass)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_accslvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_id)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel11)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rep_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(combo_accslvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_accslvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_accslvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_accslvlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crear_cuenta();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        continuar = 2;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        if (txt_pass.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_passKeyTyped

    private void txt_rep_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rep_passKeyTyped
        if (txt_rep_pass.getText().length() >= 40) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_rep_passKeyTyped

    private void txt_rep_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rep_passActionPerformed
        crear_cuenta();
    }//GEN-LAST:event_txt_rep_passActionPerformed

    public void crear_cuenta() {
        if ("".equals(txt_id.getText()) || "".equals(txt_username.getText()) || "".equals(txt_pass.getText()) || "".equals(txt_rep_pass.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡CUIDADO FALTAN DATOS!</h1><font SIZE=5><p> Falta escribir algún dato en tu formulario, verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
        } else if (!txt_pass.getText().equals(txt_rep_pass.getText())) {
            JOptionPane.showMessageDialog(null, "<html><h1>CONTRASEÑAS NO COINCIDEN</h1><font SIZE=5><p> verifique y vuelva a intentarlo</font></html>", "¡Atención!", JOptionPane.WARNING_MESSAGE);
            txt_rep_pass.setText("");
            txt_rep_pass.requestFocus();
        } else {
            int dialogButton = JOptionPane.showConfirmDialog(null, "<html><h1>¿CREAR CUENTA?  </h1><font SIZE=5><p> Verifique bien sus datos antes de continuar…</font></html>", "CREAR NUEVA CUENTA", JOptionPane.OK_CANCEL_OPTION);
            if (dialogButton == JOptionPane.OK_OPTION) {
                String id = new Encryptor().clearText(txt_id.getText().replace(',', ' '));
                String usuario = new Encryptor().clearText(txt_username.getText().replace(',', ' '));
                String pwd = new Encryptor().clearText(txt_pass.getText().replace(',', ' '));
                if (new Usuarios().existUser(usuario)) {
                    JOptionPane.showMessageDialog(this, "El usuario " + txt_username.getText().replace(',', ' ') + " ya esta registrado... vuelva a intentarlo", "¡Atención!", JOptionPane.WARNING_MESSAGE);
                } else {
                    String nuevo_registro = id + "," + usuario + "," + pwd + "," + combo_accslvl.getSelectedItem().toString() + ",";                    
                    if (new Usuarios().InsertUser(nuevo_registro)) {
                        ok = true;
                        JOptionPane.showMessageDialog(null, "<html><h1>CUENTA CREADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    }
                }
            }
        }
    }

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        txt_rep_pass.requestFocus();
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        String cadena = (txt_pass.getText()).toUpperCase();
        txt_pass.setText(cadena);
        if (txt_pass.getText().isEmpty()) {
            txt_pass.setBackground(txt_username.getBackground());
            txt_pass.setForeground(txt_username.getForeground());
        } else {
            if (txt_pass.getText().length() <= 3) {
                txt_pass.setBackground(Color.red);
                txt_pass.setForeground(Color.white);
            } else if (txt_pass.getText().length() > 3 && txt_pass.getText().length() < 6) {
                txt_pass.setBackground(Color.yellow);
                txt_pass.setForeground(Color.black);
            } else {
                txt_pass.setBackground(txt_username.getBackground());
                txt_pass.setForeground(txt_username.getForeground());
            }
        }
    }//GEN-LAST:event_txt_passKeyReleased

    private void txt_rep_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rep_passKeyReleased
        String cadena = (txt_rep_pass.getText()).toUpperCase();
        txt_rep_pass.setText(cadena);
        if (txt_rep_pass.getText().isEmpty()) {
            txt_rep_pass.setBackground(txt_username.getBackground());
            txt_rep_pass.setForeground(txt_username.getForeground());
        } else {
            if (!txt_rep_pass.getText().equals(txt_pass.getText())) {
                txt_rep_pass.setBackground(Color.red);
                txt_rep_pass.setForeground(Color.white);
            } else {
                txt_rep_pass.setBackground(txt_username.getBackground());
                txt_rep_pass.setForeground(txt_username.getForeground());
            }
        }
    }//GEN-LAST:event_txt_rep_passKeyReleased

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        txt_pass.requestFocus();
    }//GEN-LAST:event_txt_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsUser dialog = new InsUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_accslvl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_id;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_rep_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
