/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs;

import Classes.Browser;
import Classes.Clientes;
import Classes.ConfigDat;
import Classes.Polizas;
import Classes.Vehiculos;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author OSBAL
 */
public class NewPoliza extends javax.swing.JDialog {

    /**
     * Creates new form NewPoliza
     */
    public NewPoliza(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblLogo.setIcon(new ConfigDat().getDocumentLogo(lblLogo.getWidth(), lblLogo.getHeight()));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        loadClients();
        loadVehicles();
    }

    int save = 0;

    public int getSave() {
        return this.save;
    }

    public void insertPoliza() {
        this.setTitle("NUEVO POLIZA");
        btnBorrar.setVisible(false);
        lblIDReg.setText(new Polizas().genID());
    }

    public void updatePoliza(String id) {
        try {
            this.setTitle("VER POLIZA");
            btnAceptar.setText("ACTUALIZAR");
            btnBorrar.setVisible(true);
            String[] Poliza = new Polizas().getPolizabyID(id);
            lblIDReg.setText(Poliza[0]);
            txtnumPoliza.setText(Poliza[1]);
            jdcFechaVencimiento.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(Poliza[2]));
            cmbClients.setSelectedItem(Poliza[3]);
            cmbVehicles.setSelectedItem(Poliza[4]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    public void loadVehicles() {
        cmbVehicles.removeAllItems();
        List Vehicles = new Vehiculos().loadVehicles();
        if (Vehicles.isEmpty()) {
            cmbVehicles.addItem("SIN VEHICULOS");
            cmbVehicles.addItem("+ Nuevo Vehiculo");
        } else {
            for (int i = 0; i < Vehicles.size(); i++) {
                cmbVehicles.addItem(Vehicles.get(i).toString());
            }
            cmbVehicles.addItem("+ Nuevo Vehiculo");
        }
    }

    public void loadClients() {
        cmbClients.removeAllItems();
        List clientes = new Clientes().loadClientes();
        if (clientes.isEmpty()) {
            cmbClients.addItem("SIN CLIENTES");
            cmbClients.addItem("+ Nuevo Cliente");
        } else {
            for (int i = 0; i < clientes.size(); i++) {
                cmbClients.addItem(clientes.get(i).toString());
            }
            cmbClients.addItem("+ Nuevo Cliente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblIDReg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnumPoliza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbClients = new javax.swing.JComboBox<>();
        cmbVehicles = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClient = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVehicle = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jdcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Poliza"));

        lblIDReg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIDReg.setText("000000000000");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID REGISTRO");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("NUMERO DE POLIZA");

        jLabel5.setText("CLIENTE");

        jLabel6.setText("VEHICULO");

        cmbClients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientsActionPerformed(evt);
            }
        });

        cmbVehicles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVehiclesActionPerformed(evt);
            }
        });

        txtClient.setEditable(false);
        txtClient.setColumns(20);
        txtClient.setLineWrap(true);
        txtClient.setRows(5);
        jScrollPane1.setViewportView(txtClient);

        txtVehicle.setEditable(false);
        txtVehicle.setColumns(20);
        txtVehicle.setLineWrap(true);
        txtVehicle.setRows(5);
        jScrollPane2.setViewportView(txtVehicle);

        jLabel7.setText("FECHA DE VENCIMIENTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnumPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbClients, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbVehicles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIDReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAceptar.setText("GUARDAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnBorrar.setText("ELIMINAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAceptar)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientsActionPerformed
        if (cmbClients.getItemCount() > 0) {
            cmbActionPreformed(cmbClients.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbClientsActionPerformed

    private void cmbVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehiclesActionPerformed
        if (cmbVehicles.getItemCount() > 0) {
            cmbActionPreformed2(cmbVehicles.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbVehiclesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        savePoliza();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        delPoliza();
    }//GEN-LAST:event_btnBorrarActionPerformed

    public void delPoliza() {
        int dialogButton = JOptionPane.showConfirmDialog(null, "Desea borrar este Vehiculo?", "BORRAR VEHICULO", JOptionPane.YES_NO_OPTION);
        if (dialogButton == 0) {
            if (new Polizas().DelPoliza(lblIDReg.getText())) {
                JOptionPane.showMessageDialog(null, "<html><h1>POLIZA ELIMINADA CORRECTAMENTE</h1><font SIZE=5><p> Clic para cerrar</font></html>", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                new Browser().updateBrowserDB();
            }
        }
    }
    
    public boolean isChooserEmpty(JDateChooser comp) {
        boolean resp = false;
        if (comp.getDate() == null) {
            resp = true;
        }
        return resp;
    }

    public boolean compCacillas() {
        boolean resp = false;
        if ("".equals(txtnumPoliza.getText())) {
            txtnumPoliza.requestFocus();
            resp = true;
        } else if (isChooserEmpty(jdcFechaVencimiento)) {
            jdcFechaVencimiento.requestFocus();
            resp = true;
        } else if ("SIN CLIENTES".equals(cmbClients.getSelectedItem().toString())) {
            cmbClients.requestFocus();
            resp = true;
        } else if ("SIN VEHICULOS".equals(cmbVehicles.getSelectedItem().toString())) {
            cmbVehicles.requestFocus();
            resp = true;
        }
        return resp;
    }

    public void savePoliza() {
        if (!compCacillas()) {
            save = 1;
            String nreg = lblIDReg.getText()
                    + "," + txtnumPoliza.getText().replace(",", " ")
                    + "," + new SimpleDateFormat("dd-MM-YYYY").format(jdcFechaVencimiento.getDate())
                    + "," + cmbClients.getSelectedItem().toString()
                    + "," + cmbVehicles.getSelectedItem().toString()
                    + "," + new SimpleDateFormat("dd-MM-YYYY").format(new Date()) + ",";
            if (btnAceptar.getText().equals("GUARDAR")) {
                try {
                    new Polizas().insPoliza(nreg);
                    JOptionPane.showMessageDialog(this, "NUEVA POLIZA REGISTRADA CORRECTAMENTE", "INSERTAR POLIZA", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e);
                }
                new Browser().updateBrowserDB();
            } else {
                try {
                    int dialogButton = JOptionPane.showConfirmDialog(null, "DESEA ACTUALIZAR LA POLIZA SELECCIONADA?", "ACTUALIZAR POLIZA", JOptionPane.YES_NO_OPTION);
                    if (dialogButton == 0) {
                        new Polizas().updatePoliza(nreg);
                        JOptionPane.showMessageDialog(this, "POLIZA ACTUALIZADA CORRECTAMENTE", "ACTUALIZAR POLIZA", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e);
                }
                new Browser().updateBrowserDB();
            }
        }
        new Browser().updateBrowserDB();
    }

    public void cmbActionPreformed2(String Item) {
        if (Item.equals("+ Nuevo Vehiculo")) {
            insVehicle();
        }
        txtVehicle.setText(new Vehiculos().getVehicleToString(cmbVehicles.getSelectedItem().toString()));
//        actualizarResumen();
    }

    public void cmbActionPreformed(String Item) {
        if (Item.equals("+ Nuevo Cliente")) {
            insClient();
        }
        txtClient.setText(new Clientes().getClientToString(cmbClients.getSelectedItem().toString()));
//        actualizarResumen();
    }

    public void insVehicle() {
        NewVehicle ic = new NewVehicle(null, true);
        ic.insertVehicle();
        ic.show();
        String Vehicle = "";
        if (ic.getSave() == 1) {
            Vehicle = ic.getIDCar();
        }
        loadVehicles();
        cmbVehicles.setSelectedItem(Vehicle);
    }

    public void insClient() {
        NewClient ic = new NewClient(null, true);
        ic.insertClient();
        ic.show();
        String Client = "";
        if (ic.getSave() == 1) {
            Client = ic.getIdClient();
        }
        loadClients();
        cmbClients.setSelectedItem(Client);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewPoliza dialog = new NewPoliza(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JComboBox<String> cmbClients;
    private javax.swing.JComboBox<String> cmbVehicles;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFechaVencimiento;
    private javax.swing.JLabel lblIDReg;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextArea txtClient;
    private javax.swing.JTextArea txtVehicle;
    private javax.swing.JTextField txtnumPoliza;
    // End of variables declaration//GEN-END:variables
}
