/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.*;
import Dialogs.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OSBAL
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
//    int cont_mes = 0; //0 = hoy
    String[] dias = new String[45];
    DefaultTableModel modelo;

    public main() {
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                Salir();
            }
        });
        menuROOT.setVisible(false);
        setIconImage(new ConfigDat().getImageIcon().getImage());
        this.setLocationRelativeTo(null);
        this.setTitle("BIENVENIDO A INSURANCE POLICY ADMINISTRATION FREE");
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    public void showallBrowser() {
        modelo.setRowCount(0);
        String datos[] = new Browser().getDBBrowser();
        try {
            if (datos != null) {
                for (int i = 0; i < datos.length; i++) {
                    modelo.addRow(datos[i].split(","));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void inicializeTable() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if (columnas < 0) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        modelo.addColumn("ID Registro");
        modelo.addColumn("Poliza");
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("Vehiculo");
        modelo.addColumn("Num. Placa");
        modelo.addColumn("Num. Economico");
        modelo.addColumn("Fecha Vencimiento");
        tblBrowser.setModel(modelo);
        showallBrowser();
        ajustarColumnas();
    }

    public void permisos(String permisos) {
        if (!permisos.toLowerCase().equals("administrador")) {
            menuCuentas.setVisible(false);
            menuTools.setVisible(false);
            menuClients.setVisible(false);
            menuVehicles.setVisible(false);
            menuPolizas.setVisible(false);
            jMenuItem10.setVisible(false);
        }
    }

    public void Inicialize(String USer, String permisos) {
        try {
            cargar_logo();
            lblUser.setText(USer);
            inicializeTable();
            permisos(permisos);
            if (USer.toLowerCase().equals("root")) {
                menuROOT.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }

    public String getSelectDate(String dia, int mes) {
        String resp = "";
        try {
            java.util.Calendar c1 = java.util.Calendar.getInstance();
//            c1.add(java.util.Calendar.MONTH, cont_mes + 1);
            resp = c1.get(Calendar.YEAR) + "-" + c1.get(Calendar.MONTH) + "-" + dia;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
        return resp;
    }

    public boolean arePending(String fecha) {
        //FALTA REVISAR PENDIENTES DEL DIA
        boolean resp = false;

        return resp;
    }

    public String setDateFormat(java.util.Date fecha) {
        String resp = "";
        SimpleDateFormat sdf = new SimpleDateFormat("MMMMM, yyyy");
        resp = sdf.format(fecha).toUpperCase();
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_permisos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtBrowser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrowser = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mitemCerrarSesion = new javax.swing.JMenuItem();
        mitemSalir = new javax.swing.JMenuItem();
        menuCuentas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mitemAllAccounts = new javax.swing.JMenuItem();
        menuClients = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuVehicles = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuPolizas = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuROOT = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SESION INICIADA");

        lbl_permisos.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lbl_permisos.setText("AMDIN");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel6.setText("PUESTO");

        lblUser.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        lblUser.setText("USUARIO");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setText("USUARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_permisos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_permisos))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtBrowser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBrowser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrowserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBrowserKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("BUSCAR");

        tblBrowser.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tblBrowser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBrowser.setEditingColumn(0);
        tblBrowser.setEditingRow(0);
        tblBrowser.setRowHeight(19);
        tblBrowser.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tblBrowser.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBrowser);

        btnPrint.setText("IMPRIMIR");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrint, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuArchivo.setText("Archivo");

        mitemCerrarSesion.setText("Cerrar Sesion");
        mitemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCerrarSesionActionPerformed(evt);
            }
        });
        menuArchivo.add(mitemCerrarSesion);

        mitemSalir.setText("Salir");
        mitemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(mitemSalir);

        jMenuBar1.add(menuArchivo);

        menuCuentas.setText("Cuentas");

        jMenuItem1.setText("Todas las Cuentas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCuentas.add(jMenuItem1);

        mitemAllAccounts.setText("Registro Sesiones");
        mitemAllAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemAllAccountsActionPerformed(evt);
            }
        });
        menuCuentas.add(mitemAllAccounts);

        jMenuBar1.add(menuCuentas);

        menuClients.setText("Clientes");

        jMenuItem3.setText("Nuevo Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuClients.add(jMenuItem3);

        jMenuItem6.setText("Registro de Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuClients.add(jMenuItem6);

        jMenuBar1.add(menuClients);

        menuVehicles.setText("Vehiculos");

        jMenuItem4.setText("Nuevo Vehiculo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuVehicles.add(jMenuItem4);

        jMenuItem8.setText("Registro de Vehiculos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuVehicles.add(jMenuItem8);

        jMenuBar1.add(menuVehicles);

        menuPolizas.setText("Polizas");

        jMenuItem7.setText("Nueva Poliza");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuPolizas.add(jMenuItem7);

        jMenuItem9.setText("Registro de Polizas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuPolizas.add(jMenuItem9);

        jMenuBar1.add(menuPolizas);

        menuTools.setText("Herramientas");

        jMenuItem5.setText("Respaldo del sistema");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem5);

        jMenuItem11.setText("Modo de fabrica");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuTools.add(jMenuItem11);

        menuROOT.setText("==ROOT TOOLS==");

        jMenuItem14.setText("EncryptDecrypt");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menuROOT.add(jMenuItem14);

        menuTools.add(menuROOT);

        jMenuBar1.add(menuTools);

        menuAbout.setText("Acerca de");

        jMenuItem10.setText("Datos de la Empresa");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuAbout.add(jMenuItem10);

        jMenuItem2.setText("Info. de producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAbout.add(jMenuItem2);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSalirActionPerformed
        Salir();
    }//GEN-LAST:event_mitemSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        infoProd();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mitemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCerrarSesionActionPerformed
        cerrarSesion();
    }//GEN-LAST:event_mitemCerrarSesionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        NewClient ic = new NewClient(this, true);
        ic.insertClient();
        ic.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mitemAllAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemAllAccountsActionPerformed
        new AllSessions().show();
    }//GEN-LAST:event_mitemAllAccountsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AllUsers au = new AllUsers();
        au.setCurrentuser(lblUser.getText());
        au.showAccounts();
        au.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        AllClients ac = new AllClients();
        ac.showClients();
        ac.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Confirm c = new Confirm(this, true);
        c.setVisible(true);
        if (c.getResp() == 1) {
            int resp = JOptionPane.showConfirmDialog(null, "<html><h1>¡RESPALDO DE SISTEMA!</h1><font SIZE=5><p>¿Seguro desea respaldar su base de datos?<p></font></html>", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                new SystemRecovery().SystemBackup();
            }
        } else if (c.getResp() == 0) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡ACCESO DENEGADO!</h1><font SIZE=5><p>Verifique sus credenciales...</font></html>", "¡Atencion!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        new EncryptDecrypt(this, true).show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void txtBrowserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrowserKeyReleased
        if (!txtBrowser.getText().equals("")) {
            browserAction(txtBrowser.getText());
        } else {
            showallBrowser();
        }
    }//GEN-LAST:event_txtBrowserKeyReleased

    public void ajustarColumnas() {
        tblBrowser.setRowHeight(40);
    }

    public void browserAction(String indicio) {
        modelo.setRowCount(0);
        try {
            String datos[] = new Browser().getDBBgsrRegistry(indicio);
            if (datos != null) {
                for (int i = 0; i < datos.length; i++) {
                    modelo.addRow(datos[i].split(","));
                }
            } else {
                modelo.setRowCount(0);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txtBrowserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrowserKeyTyped
        if (((int) evt.getKeyChar() > 33 && (int) evt.getKeyChar() <= 47) || ((int) evt.getKeyChar() > 57 && (int) evt.getKeyChar() <= 64) || ((int) evt.getKeyChar() > 90 && (int) evt.getKeyChar() <= 96) || ((int) evt.getKeyChar() > 122 && (int) evt.getKeyChar() <= 255)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBrowserKeyTyped

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        NewVehicle nv = new NewVehicle(this, true);
        nv.insertVehicle();
        nv.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        NewPoliza np = new NewPoliza(this, true);
        np.insertPoliza();
        np.show();
        new Browser().updateBrowserDB();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        printDocument();
    }//GEN-LAST:event_btnPrintActionPerformed

    public void printDocument() {
        try {
            if (tblBrowser.getRowCount() > 0) {
                //DatGen[0] == idDoc
                //DatGen[1] == nomCliente
                //DatGen[2] == Usuario
                //DatGen[3] == Pie de pagina 
                String[] DatGen = new String[5];
                DatGen[0] = new DPFDocs().genID();
                DatGen[1] = "sin Datos";
                DatGen[2] = lblUser.getText();
                DatGen[3] = "Pie de pagina";

                String[] registros = getDataTableContent();
                PrintDocs pd = new PrintDocs(this, true);
                pd.setData();
                pd.show();
                if (pd.isOk()) {
                    new DPFDocs().printDocument(DatGen, registros, pd.getImpresora());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error main: " + e);
        }
    }

    public String[] getDataTableContent() {
        String[] resp = new String[tblBrowser.getRowCount()];
        for (int i = 0; i < resp.length; i++) {
            String nreg = "";
            for (int j = 0; j < tblBrowser.getColumnCount(); j++) {
                nreg += tblBrowser.getValueAt(i, j).toString() + ",";
            }
            resp[i] = nreg;
        }
        return resp;
    }

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        AllVehicles av = new AllVehicles();
        av.showVehicles();
        av.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        AllPolizas ap = new AllPolizas();
        ap.showPolizas();
        ap.show();
        new Browser().updateBrowserDB();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Datos_Tienda_2 mdt = new Datos_Tienda_2(this, true);
        mdt.asignar_datos();
        mdt.show();
        if (mdt.isOk()) {
            act_datos_tienda();
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Confirm c = new Confirm(this, true);
        c.setVisible(true);
        if (c.getResp() == 1) {
            int resp = JOptionPane.showConfirmDialog(null, "<html><h1>¡RESETEAR A MODO FABRICA!</h1><font SIZE=5><p>¿Seguro desea poner en modo de fabrica la aplicación?<p><p>Se perderán todos los datos y archivos que se hayan generado<p>mientras se uso de esta App</font></html>", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                new ConfigDat().setFiratUse("desactivado");
                JOptionPane.showMessageDialog(null, "<html><h1>¡RESTAURAR A MODO DE FABRICA!</h1><font SIZE=5><p>Se requiere iniciar manualmente la aplicación para restablecer el sistema...</font></html>", "", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
        } else if (c.getResp() == 0) {
            JOptionPane.showMessageDialog(null, "<html><h1>¡ACCESO DENEGADO!</h1><font SIZE=5><p>Verifique sus credenciales...</font></html>", "¡Atencion!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed
    public void act_datos_tienda() {
        String[] datos = new DatEmpresa().getDatEmpresa();
        for (int i = 0; i < datos.length; i++) {
            System.out.println(datos[i]);
        }
//        this.setTitle("Caja Registradora " + datos[1]);
    }

    public void cerrarSesion() {
        int resp = JOptionPane.showConfirmDialog(null, "<html><h1>CERRAR SESION</h1><font SIZE=5><p>Se perderán todos los datos que no se hayan guardado… ¿desea continuar? </font></html>", "Cerrar Sesion!", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            dispose();
            Login cs = new Login();
            cs.show();
        }
    }

    public void infoProd() {
        try {
            JOptionPane.showMessageDialog(null, "<html><h1>Información del producto:</h1><font SIZE=5><p>***<b>Insurance Policy Administration FREE v1.5.0</b> ***<p>Titular de la cuenta: <b>Yo mero</b> <p>Dirección: <b>Enrique segobiano</b><p>Clave de producto: <b>123456</b><p><p><b><center>Desarrollado por</b></center><p>Osbaldo Toledo Ramos - PTB en Informática<p>E-Mail: <b>osbaldo.toledoramos@hotmail.com</b><p><center><i>Prepare for Unforeseen Consequences<p></font></html>", "¡Info. de producto!", JOptionPane.INFORMATION_MESSAGE);
            new Publicidad(null, true).show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void cargar_logo() {
        try {
            lblLogo.setIcon(new ConfigDat().getLogo(lblLogo.getWidth(), lblLogo.getHeight()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e, "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Salir() {
        int resp = JOptionPane.showConfirmDialog(null, "<html><h1>SALIR DE LA APLICACIÓN</h1><font SIZE=5><p>Se perderán todos los datos que no se hayan guardado… ¿desea continuar? </font></html>", "Salir", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            System.exit(resp);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbl_permisos;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuClients;
    private javax.swing.JMenu menuCuentas;
    private javax.swing.JMenu menuPolizas;
    private javax.swing.JMenu menuROOT;
    private javax.swing.JMenu menuTools;
    private javax.swing.JMenu menuVehicles;
    private javax.swing.JMenuItem mitemAllAccounts;
    private javax.swing.JMenuItem mitemCerrarSesion;
    private javax.swing.JMenuItem mitemSalir;
    private javax.swing.JTable tblBrowser;
    private javax.swing.JTextField txtBrowser;
    // End of variables declaration//GEN-END:variables
}
